manifest:
  remotes:
    - name: zmk-config-corne
      url-base: https://github.com/yunsuk-jeung
      revision: test_zmk
  projects:
    - name: zmk-config-corne
      remote:  https://github.com/yunsuk-jeung
      revision: test_zmk
      import: config/west.yml
  self:
    path: config
